services:
  mysql:
    image: mysql:8.0
    container_name: cms-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: master
      MYSQL_DATABASE: cms_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: cms-backend:1.0
    container_name: cms-backend
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped

volumes:
  mysql_data:
